### ISSUE TITLE
Error running MQTT in docker

### ISSUE THREAD

**Issue by lindehoff** [molobrakos/volvooncall#33]
Hi,
When I try to run  `./voc mqtt` in the docker container I get un error:
```
Traceback (most recent call last):
  File "./voc", line 235, in <module>
    main()
  File "./voc", line 231, in main
    run(connection, credentials)
  File "/app/mqtt.py", line 407, in run
    port=int(mqtt_config['port']))
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 994, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

This is how I run it:
```bash
docker build -t molobrakos/voc .
docker run --name=voc --restart=always --detach --net=bridge  -v <full path to voc.conf>:/app/.config/voc.conf:ro -v <full path to mosquitto_pub>:/app/.config/mosquitto_pub:ro molobrakos/voc -vv
```
 When I the look at `docker logs voc`:
```
<First a dump from VoC, with all my cars data>
Traceback (most recent call last):
  File "./voc", line 235, in <module>
    main()
  File "./voc", line 231, in main
    run(connection, credentials)
  File "/app/mqtt.py", line 407, in run
    port=int(mqtt_config['port']))
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 994, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

**Comment by lindehoff** [comment]
If I delete https://github.com/molobrakos/volvooncall/blob/aef17ca3afe234a2b707fd48f4aae631e0e93de6/mqtt.py#L396 and rebuild the docker image and run the same command as before it seems to work.

**Comment by molobrakos** [comment]
It currently assumes an SSL enabled MQTT broker. The error message (and documentation) could be better ... (I would accept any PR that fixes this).
