### ISSUE TITLE
Trigger command with mosquitto_pub

### ISSUE THREAD

**Issue by lindehoff** [molobrakos/volvooncall#34]
I'm trying to figure out how to trigger a command with `mosquitto_pub`.
I have tried to run `mosquitto_pub  -t "volvo/<REG_NR>/heater/cmd" -m "{'on': true}"`
If I run voc with `./voc mqtt -vv` and the run the mosquitto_pub command I get en error
```
Exception in thread MQTTThread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2913, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1578, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1072, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1374, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2071, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2560, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2759, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2902, in _handle_on_message
    callback(self, self._userdata, message)
TypeError: on_mqtt_message() takes 3 positional arguments but 4 were given
```
So I'm guessing I'm doing something wrong with the publish command. I can not seem to find any documentation around this and hoping it's OK to ask questions here.

**Comment by molobrakos** [comment]
Hopefully works better with latest commit.

**Comment by molobrakos** [comment]
Closing for now, please re-open if still a problem.
