### ISSUE TITLE
voc dashboard

### ISSUE THREAD

**Issue by staskray** [molobrakos/volvooncall#36]
voc dashboard does not handle my Volvo V90 T8 supported features set properly. 
When I run it with -vv debug option, last lines are:

18-11-30 08:32.13 DEBUG (MainThread) [dashboard] Setting up dashboard with config :{'username': 's****y@gmail.com', 'password': '******', 'interval': '300', 'scandinavian_miles': False, 'immutable': False}
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Position is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Door lock is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Heater is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Odometer is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Trip meter 1 is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Trip meter 2 is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Fuel amount is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Fuel level is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Fuel consumption is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Range is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Battery range is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Battery level is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Time to fully charged is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Battery charging is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Engine is supported
18-11-30 08:32.13 DEBUG (MainThread) [dashboard] ILL-329 Last trip is supported
Traceback (most recent call last):
  File "./voc", line 269, in <module>
    run(main(args), debug=debug)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "./voc", line 219, in main
    dashboard = vehicle.dashboard(**credentials)
  File "/Users/skrainik/Private/volvooncall/volvooncall.py", line 415, in dashboard
    return Dashboard(self, **config)
  File "/Users/skrainik/Private/volvooncall/dashboard.py", line 477, in __init__
    for instrument in create_instruments()
  File "/Users/skrainik/Private/volvooncall/dashboard.py", line 478, in <listcomp>
    if instrument.setup(vehicle, **config)
  File "/Users/skrainik/Private/volvooncall/dashboard.py", line 38, in setup
    if not self.is_supported:
  File "/Users/skrainik/Private/volvooncall/dashboard.py", line 66, in is_supported
    if hasattr(self.vehicle, self.attr):
  File "/Users/skrainik/Private/volvooncall/volvooncall.py", line 251, in is_engine_running
    'on' in engine_remote_start_status)
TypeError: argument of type 'NoneType' is not iterable

**Comment by molobrakos** [comment]
Hopefully fixed here https://github.com/molobrakos/volvooncall/commit/4a2bd02767302776c6d89d11d8df576bb2814ade

**Comment by staskray** [comment]
thanks for fast fix, it works.
