### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by Plarkass** [molobrakos/volvooncall#55]
Hi,

I got an issue when trying to get status of my car.

At begining, i think it was a password issue but even if i change it, i got same issue.

I am on Europe servers, i try with -r eu but same issue.

ogiffard@LAPTOP741618:~/GIT/volvooncall$ voc -u "************@g*****l.com" -p "********" status
Traceback (most recent call last):
  File "/usr/local/bin/voc", line 4, in <module>
    __import__('pkg_resources').run_script('volvooncall==0.8.12', 'voc')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/volvooncall-0.8.12-py3.6.egg/EGG-INFO/scripts/voc", line 291, in <module>
    run(main(args), debug=debug)
  File "/usr/local/lib/python3.6/dist-packages/volvooncall-0.8.12-py3.6.egg/EGG-INFO/scripts/voc", line 283, in run
    loop.run_until_complete(fut)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/volvooncall-0.8.12-py3.6.egg/EGG-INFO/scripts/voc", line 152, in main
    res = await connection.update(journal=journal)
  File "/usr/local/lib/python3.6/dist-packages/volvooncall-0.8.12-py3.6.egg/volvooncall/volvooncall.py", line 105, in update
    user = await self.get("customeraccounts")
  File "/usr/local/lib/python3.6/dist-packages/volvooncall-0.8.12-py3.6.egg/volvooncall/volvooncall.py", line 91, in get
    return await self._request(METH_GET, self._make_url(url, rel))
  File "/usr/local/lib/python3.6/dist-packages/volvooncall-0.8.12-py3.6.egg/volvooncall/volvooncall.py", line 76, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-4.0.0a0-py3.6-linux-x86_64.egg/aiohttp/client_reqrep.py", line 942, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized'

**Comment by decompil3d** [comment]
I've heard of cases where the password contains characters that need escaping. Perhaps that was it?
